# Generated by Django 5.0.1 on 2024-01-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hps_EnergySim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
    ]
